# Generated by Django 5.1 on 2024-11-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Karyawan', '0003_karyawan_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='notifikasi_telegram',
            field=models.BooleanField(default=False),
        ),
    ]
