# Generated by Django 5.1 on 2024-11-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Siswa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='notifikasi_telegram',
            field=models.BooleanField(default=False),
        ),
    ]
