from .dashboard_absensi import *
from .atribut import *
from .sakit import *
from .izin import *
from .pengaturan import *
from .verifikasi import *
from .admin_siswa import *
from .admin_guru import *
from .admin_karyawan import *
