from .atribut import *
from .sakit import *
from .izin import *
from .pengaturan import *
from .verifikasi import *
from .admin_siswa import *
from .admin_guru import *
from .admin_karyawan import *
from .tamer import *
from .dashboard_absensi_karyawan import *
from .dashboard_absensi_guru import *
from .dashboard_absensi_siswa import *
from .dashboard_absensi import *
