# Generated by Django 5.1 on 2024-09-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalasi',
            name='jam_masuk',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalasi',
            name='jam_pulang',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record_absensi',
            name='tipe_absensi',
            field=models.CharField(choices=[('masuk', 'Masuk'), ('pulang', 'Pulang')], default='masuk', max_length=20),
        ),
    ]
