# Generated by Django 5.1 on 2024-09-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_instalasi_jam_masuk_instalasi_jam_pulang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_absensi',
            name='tipe_absensi',
            field=models.CharField(blank=True, choices=[('masuk', 'Masuk'), ('pulang', 'Pulang')], max_length=20, null=True),
        ),
    ]
