# Generated by Django 5.1 on 2024-09-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_record_absensi_tipe_absensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalasi',
            name='jam_kerja',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
