# Generated by Django 5.1 on 2024-09-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_instalasi_jam_kerja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalasi',
            name='jam_kerja',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
