# Generated by Django 5.1 on 2024-11-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_record_absensi_terlambat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instalasi',
            old_name='jam_kerja',
            new_name='jam_kerja_guru',
        ),
        migrations.RenameField(
            model_name='instalasi',
            old_name='jam_masuk',
            new_name='jam_masuk_guru',
        ),
        migrations.RenameField(
            model_name='instalasi',
            old_name='jam_pulang',
            new_name='jam_masuk_karyawan',
        ),
        migrations.AddField(
            model_name='instalasi',
            name='jam_kerja_karyawan',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalasi',
            name='jam_masuk_siswa',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalasi',
            name='jam_pulang_guru',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalasi',
            name='jam_pulang_karyawan',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalasi',
            name='jam_pulang_siswa',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalasi',
            name='jam_sekolah_siswa',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
