# Generated by Django 5.1 on 2024-12-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_jam_kerja_instalasi_jam_kerja_guru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_absensi',
            name='mesin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
